name: Chrome headless

on: push

jobs:
    chrome-headless:
        runs-on: ubuntu-18.04
        container: cypress/browsers:node14.16.0-chrome90-ff88
        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Install the project
              run: npm ci

            - name: Headless Chrome
              timeout-minutes: 5
              continue-on-error: true
              run: npm run cypress:chrome

            - name: Copy test execution videos
              run: |
                  mkdir public
                  cp -r cypress/videos public/videos

            - name: Generate Report
              run: |
                  npm run report:merge
                  npm run report:generate

            - name: Deploy report to Github Pages
              if: always()
              uses: peaceiris/actions-gh-pages@v2
              env:
                  PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PUBLISH_BRANCH: gh-pages
                  PUBLISH_DIR: ./public
